version: '3'

services:
  postgres:
    container_name: postgres_container
    image: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "OAuthServer"
      POSTGRES_USER: "rooted"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 2G
  keycloak:
    container_name: keycloak_container
    image: quay.io/keycloak/keycloak:latest
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: OAuthServer
      DB_USER: rooted
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_HOSTNAME: auth-server
      KEYCLOAK_USER: yarik
      KEYCLOAK_PASSWORD: 45567899
    ports:
      - 8081:8081
    depends_on:
      - postgres